# default values
all:
  iceMultimediaPlugin:
    default_adapter: GD 
    default_image:
      mime_type: image/jpg
      filename: Untitled.png
      width: 100
      height: 100
      color: '#FFFFFF'
    font_dir: /usr/share/fonts/truetype/msttcorefonts
    mime_type:
      auto_detect: true
      library: gd_mime_type
