connection: propel
noXsd: false
defaultIdMethod: native
package: plugins.iceMultimediaPlugin.lib.model
encoding: utf8

classes:
  Multimedia:
    phpName: iceModelMultimedia
    columns:
      id:  ~
      model:       { type: char, size: 64, required: true }
      model_id:    { type: integer }
      type:        { type: char, sqlType: "ENUM('image','video','pdf')", default: image, required: true }
      name:        { type: char, size: 128, required: true, primaryString: true }
      slug:        { type: char, size: 128, required: true, index: unique }
      md5:         { type: char, size: 32, required: true }
      source:      { type: varchar(255), required: false }
      is_primary:  { type: boolean, sqlType: "BOOL", default: false }
      position:    { type: smallint, sqlType: "SMALLINT UNSIGNED", default: 65535 }
      created_at:  ~
    indexes:
      multimedia_I_2: [model, model_id]
    uniques:
      multimedia_U_2: [model, model_id, md5]
